"""Concatenate AI-readable Markdown files into llms-full.txt.

Per https://llmstxt.org, llms-full.txt should give an LLM the full project
context in a single fetch. We concatenate the README, AGENTS.md, the
generated cheatsheet, and (when present in later phases) RECIPES.md and
PROMPTS.md.

Run:
    python scripts/build-llms-full.py
or:
    make build-llms-full
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "llms-full.txt"

SOURCES = [
    ("README.md", "Project README"),
    ("AGENTS.md", "AI-assistant guide"),
    ("AI_API_CHEATSHEET.md", "API cheatsheet"),
    ("RECIPES.md", "Task-oriented recipes (Phase 2 — optional)"),
    ("PROMPTS.md", "Prompt templates (Phase 2 — optional)"),
]


def main() -> None:
    chunks: list[str] = []
    chunks.append("# maialib — full LLM context bundle")
    chunks.append("")
    chunks.append(
        "Generated by scripts/build-llms-full.py. Concatenates the project's "
        "human + AI-facing Markdown into a single fetchable document."
    )
    chunks.append("")
    for fname, label in SOURCES:
        p = REPO / fname
        if not p.exists():
            continue
        chunks.append("=" * 72)
        chunks.append(f"# {label}  (source: {fname})")
        chunks.append("=" * 72)
        chunks.append("")
        chunks.append(p.read_text(encoding="utf-8"))
        chunks.append("")

    OUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
