#on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.111"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.4

      - name: Configure
        shell: bash
        run: >
          make module

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
