name: Build Wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pybind11-stubgen==2.5.1 mypy cibuildwheel

      - name: Install maialib
        run: python -m pip install .

      - name: Generate stubs from Maiacore
        run: pybind11-stubgen maialib.maiacore --output-dir=./stubs/ --ignore-invalid-expressions ".*" --ignore-all-errors

      - name: Generate stubs from Maiapy
        run: stubgen ./maialib/maiapy/ -o ./stubs/

      - uses: pypa/cibuildwheel@v2.11.3
        with:
          output-dir: wheelhouse
        env:
          CIBW_ARCHS_MACOS: auto universal2
          CIBW_BEFORE_ALL_LINUX: cp -rf ./stubs/* .
          CIBW_BEFORE_ALL_MACOS: cp -rf ./stubs/* .
          CIBW_BEFORE_ALL_WINDOWS: xcopy /e /k /y .\stubs\* .
          CIBW_SKIP: cp36-* cp37-* pp37-* *-win32 *-manylinux_i686

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          retention-days: 3

  upload_all:
    name: Upload All
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.pypi_password }}
